name: fluxtube
description: "A YouTube client application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.0+11

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_links: ^6.3.3
  awesome_bottom_bar: ^1.2.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dismissible_page: ^1.0.2
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.4.2
  intl: ^0.20.2
  intl_utils: ^2.8.7
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  lottie: ^3.1.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  receive_sharing_intent: ^1.8.1
  rich_readmore: ^1.1.1
  share_plus: ^12.0.1
  file_picker: ^8.0.0
  archive: ^4.0.2
  sqflite: ^2.4.1
  path: ^1.9.1
  shimmer: ^3.0.0
  simple_html_css: ^5.0.0
  url_launcher: ^6.3.0
  open_filex: ^4.5.0
  youtube_explode_dart: ^3.0.5
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  screen_brightness: ^2.1.7
  volume_controller: ^3.4.1
  flutter_local_notifications: ^18.0.1
  audio_service: ^0.18.15

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  drift_dev: ^2.22.1

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

  localizely:
    project_id: en

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
